#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
#playerctld daemon &
$HOME/.config/polybar/launch.sh &

if [[ $(xrandr -q | grep 'HDMI-A-0 connected') ]]; then
    xrandr --output eDP --primary --mode 1920x1080 --rotate normal --output "HDMI-A-0" --mode 1920x1080 --rotate normal --left-of eDP
fi

bspc monitor eDP -d I II III
bspc monitor HDMI-A-0 -d IV V VI

bspc config border_width         0
bspc config window_gap           10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Pointer
bspc config pointer_motion_interval 40

bspc rule -a discord desktop='^2'
bspc rule -a Steam desktop='^2'
bspc rule -a lutris desktop='^2'
# Master Duel
bspc rule -a steam_app_1449850 desktop='^3' follow=on

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
